export const P = {

	BRONZE_PLAQUE: 5,
	TRADITIONAL_ENGRAVED_PLAQUE: 34,
    FULL_COLOUR_PLAQUE: 32,
    LASER_ETCHED_BLACK_GRANITE_PLAQUE: 30,
    LASER_ETCHED_BLACK_GRANITE_HEADSTONE: 4,
    LASER_ETCHED_BLACK_GRANITE_MINI_HEADSTONE: 22,
    LASER_ETCHED_PET_MINI_HEADSTONE: 8,
    LASER_ETCHED_PET_PLAQUE: 9,
    LASER_ETCHED_PET_ROCK: 135,
    YAG_LASERED_SS_PLAQUE: 52,
    TRADITIONAL_ENGRAVED_HEADSTONE: 124,
    STAINLESS_STEEL_URN: 2350, 
    CERAMIC_IMAGE: 7,
    TRADITIONAL_ENGRAVED_FULL_MONUMENT: 101,
    TRADITIONAL_ENGRAVED_HEADSTONE_3D: 102,
    LASER_ETCHED_BLACK_GRANITE_FULL_MONUMENT: 100
    
}

const language = ["ABN", "ACCOUNT", "ACCOUNT_DETAILS", "ACTUAL_COLOUR_MAY_VARY", "ADDRESS", "ADD", "ADD_NEW_LINE", "ADD_YOUR_INSCRIPTION", "ANIMALS", "AND", "AQUATIC", "ARCHITECTURAL", "ARE_YOU_SURE_YOU_WANT_TO_GO_BACK", "ARE_YOU_SURE_YOU_WANT_TO_LOGOUT", "ARE_YOUS_SURE_YOU_WANT_TO_QUICK_ENQUIRY", "ARE_YOU_SURE_YOU_WANT_TO_GO_TO_HOME_PAGE", "ARE_YOU_SURE_YOU_WANT_TO_START_NEW_DESIGN", "ARE_YOU_SURE_YOU_WANT_TO_SWITCH_MODE", "ARROW", "AUS_FLORA", "AUS_WILDLIFE", "BACKGROUND", "BACKGROUNDS", "BACKGROUND_VITREOUS_DESCRIPTION", "BACKGROUND_TRADITIONAL_DESCRIPTION", "BACKGROUND_COLOUR", "BACK_TO_DESIGN_MENU", "BACK_TO_EMBLEMS_LIST", "BACK_TO_MOTIFS_LIST", "BASE", "BIRDS", "BLACK_LID", "BORDER", "BORDERS", "BPAY", "BRONZES", "BRONZE_BACKGROUND", "BRONZE_BORDERS", "BRONZE_PLAQUE", "BRONZE_PLAQUE_SIZES", "BRONZE_PLAQUE_DESCRIPTION", "BRUSHED_FINISH", "BUSINESS_NAME", "BUTTERFLIES", "BUY", "BUYING_A_DESIGN", "CANCEL", "CONTINUE", "CARTOONS", "CARTOONS_AND_ANIMALS", "CATS", "CERAMIC_IMAGE", "CERAMIC_IMAGE_DESCRIPTION", "CERAMIC_IMAGE_OVERLAY", "CERAMIC_PHOTO", "CERAMIC_PHOTO_DESCRIPTION", "CHANGE_PASSWORD", "CHECK_PRICE", "CHECK_PRICE_2", "CHEQUE", "CHILDREN_TOYS", "CITY", "CLICK_MENU_ITEM_TO_SELECT_FIXING_SYSTEM", "CLICK_CANCEL_TO_FINISH_POSITIONING", "CLICK_HERE_TO_WATCH_A_DESIGN_YOUR_OWN_HELP_VIDEO", "CLICK_TO_ENLARGE", "CLOSE", "COLOR", "COLOR_OF_BRONZE_EMBLEMS", "COMMENTS", "COMING_SOON", "CONTACT_NUMBER", "CONTACT_PAGE", "CONTACT_FORM", "CONTACT_POPUP", "CONTACT_US", "CORNERS", "CORNERS_INFO", "COUNTRY", "COURIER", "CREATED", "CREDIT_CARD", "CROP_IMAGE", "CROP_SECTION", "CROP_SECTION_DESCRIPTION", "CURRENCY", "CUSTOMER", "CUSTOM_SHAPES", "DATE", "DECREASE", "DEGREES", "DELETE", "DELIVERY_DETAILS_INFO", "DESIGN_NAME", "DESKTOP", "DIRECT_DEPOSIT", "DOGS", "DUPLICATE", "DOWNLOAD", "EDIT", "EMAIL", "EMAIL_NOT_IN_DB", "EMAIL_ADDRESS", "EMAIL_LOGIN", "EMAIL_SENT", "EMBLEMS", "EMBLEMS_INFO", "ENTER", "ENTER_YOUR_ENQUIRY_HERE", "ENQUIRY", "ENQUIRY_SENT", "EXTRA_DURABILITY_AND_EXTRA_FASTENING", "FARM_ANIMAL", "FILE", "FIRST_NAME", "FIXING_SYSTEM", "FIXING_INFO", "FLAT_BACK", "FLAT_BACK_FOR_GLUE_FIXING", "FLIP_X", "FLIP_Y", "FLORISH", "FLOURISHES", "FLOWERS", "FLOWER_INSERTS", "FLOWER_POT_HOLES", "FOOD_AND_DRINK", "FREE", "FRUIT_AND_VEGES", "FULL_COLOUR", "FULL_COLOUR_PLAQUE", "FULL_COLOUR_PLAQUE_SIZE", "FULL_COLOUR_PLAQUE_DESCRIPTION", "FULL_COLOUR_PLAQUE_BORDER", "FULL_MONUMENT", "GOLD_LID", "GO_BACK_TO_ORDERS", "GO_BACK_TO_SAVED_DESIGNS", "GRANITE", "GRANITES", "GRANITE_IMAGE_DIRECT_ON_STONE", "GRANITE_IMAGE_DIRECT_ON_STONE_DESCRIPTION", "GREYSCALE", "GST", "GST_AUSTRALIA", "HEADSTONE", "HEADSTONE_BASE", "HEADSTONE_BORDER", "HEADSTONE_SIZES", "HEADSTONE_SIZES_TRADITIONAL", "HEARTS", "HEIGHT", "HIGH", "HIGHLY_POLISHED_FINISH", "HISTORY", "HOLES", "HOLIDAY", "HOME", "HORSES", "HOUSEHOLD_ITEMS", "ICONIC_PLACES", "IMAGE", "IMAGES", "INBUILT", "INCHES", "INCREASE", "INCREMENTAL_SIZES_ONLY", "INSCRIPTIONS", "INSCRIPTIONS_INFO_BRONZE", "INSCRIPTIONS_INFO_LASER", "INSCRIPTIONS_INFO_OTHER", "INSCRIPTIONS_INFO_TRADITIONAL", "INSCRIPTIONS_STEEL", "INSCRIPTIONS_STEEL_LIGHT_TRANSMITTING", "INSECTS", "INSTRUCTIONS", "INSTRUCTIONS_SIZES", "INSTRUCTIONS_SIZES_PET", "INSTRUCTIONS_SHAPES", "INSTRUCTIONS_BORDERS", "INSTRUCTIONS_SS_BORDERS", "INSTRUCTIONS_BACKGROUNDS", "INSTRUCTIONS_BACKGROUNDS_ENAMEL", "INSTRUCTIONS_BACKGROUNDS_SS", "INSTRUCTIONS_BACKGROUNDS_TRADITIONAL", "INSTRUCTIONS_INSCRIPTIONS", "INSTRUCTIONS_IMAGES", "INSTRUCTIONS_EMBLEMS", "INSTRUCTIONS_MOTIFS", "INSTRUCTIONS_FIXING", "INSTRUCTIONS_CORNERS", "INSTRUCTIONS_HOLES","INSTALLATIONS", "INSTALLATIONS_METHODS", "INSTALLATION_METHOD", "INVOICE_DETAILS", "ISLANDER", "ITEM_TOTAL", "LANGUAGE", "LASER_ETCHED_BLACK_GRANITE_FULL_MONUMENT", "LASER_ETCHED_BLACK_GRANITE_FULL_MONUMENT_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_HEADSTONE", "LASER_ETCHED_BLACK_GRANITE_HEADSTONE_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_MINI_HEADSTONE", "LASER_ETCHED_BLACK_GRANITE_MINI_HEADSTONE_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_PET_MINI_HEADSTONE", "LASER_ETCHED_BLACK_GRANITE_PET_MINI_HEADSTONE_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_PET_PLAQUE", "LASER_ETCHED_BLACK_GRANITE_PET_PLAQUE_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_PET_PLAQUE_SHAPES", "LASER_ETCHED_BLACK_GRANITE_PET_ROCK", "LASER_ETCHED_BLACK_GRANITE_PET_ROCK_DESCRIPTION", "LASER_ETCHED_BLACK_GRANITE_PLAQUE", "LASER_ETCHED_BLACK_GRANITE_PLAQUE_DESCRIPTION", "LASER_ETCHED_GRANITE_IMAGE", "LAST_MODIFIED", "LAST_NAME", "LENGTH", "LEDGER", "LINK_BASE", "KERBSET", "LOAD_MORE", "LOGIN", "LOGIN_AND_PASSWORD_DO_NOT_MATCH", "LOGIN_EMAIL", "LOGIN_INFO", "LOGIN_RETURNING_CUSTOMERS", "LOGIN_TO_ACCOUNT", "LOGOUT", "LUGS_WITH_STUDS", "MATERIALS", "MATERIALS_IMAGE_DESCRIPTION", "MATERIALS_IMAGE_INSTRUCTIONS", "MATERIALS_IMAGE_SIZES", "MATERIALS_IMAGE_SIZES_INSTRUCTIONS", "MAX_CHARS", "MENU", "MEASURMENT", "MEASURMENT_COLOR", "MEASURMENT_COLOR_DESCRIPTION", "MEASURMENT_DESCRIPTION", "MEDIUM", "MESSAGE", "METRIC", "MILLIMETERS", "MINI_HEADSTONE_BURIED_INTO_GROUND", "MINI_HEADSTONE_ONLY_LAY_FLAT", "MINI_HEADSTONE_WITH_GRANITE_BASE", "MM", "MOBILE", "MOON_AND_STARS", "MORE", "MOTIFS", "MOTIFS_INFO_BRONZE", "MOTIFS_INFO_LASER", "MOTIFS_INFO_TRAD", "MOTIFS_INFO_PET", "MOTIFS_INFO_STEEL", "MUSIC_AND_DANCE", "MYSTICAL_ANIMALS", "MY_ACCOUNT", "HOLES_INFO", "NO_DRILLED_HOLES", "NO_STAND", "ON_CORNERS", "ON_TOP_CORNERS", "NAUTICLE", "NEW_CUSTOMER", "NEW_DESIGN", "NEW_PASSWORD", "NO", "NONE", "NOTES", "OFFICIAL", "ONE_COLOUR_GLASS_BACKED_MOTIF", "ONE_COLOUR_GLASS_BACKED_MOTIF_DESCRIPTION", "ONE_COLOUR_RAISED_GLASS_BACKED_MOTIF", "ONE_COLOUR_RAISED_GLASS_BACKED_MOTIF_DESCRIPTION", "OLD_PASSWORD", "OR", "ORDER_ID", "ORDER_INFORMATION", "OTHER", "PASSWORD", "PASSWORD_AND_REPEAT_PASSWORD_DOES_NOT_MATCH", "PASSWORD_RESET_LINK_HAS_BEEN_SENT", "PASSWORD_HAS_BEEN_CHANGED", "PAYMENT_METHOD", "PAYMENT_OPTIONS", "PAYMENT_WAS_CANCELED", "PAYMENT_WAS_NOT_SUCCESFUL", "PAYMENT_PAYPAL", "PAYMENT_STRIPE", "PAY_BY_PHONE", "PAYPAL", "PDF", "PEOPLE", "PETS", "PET_ROCK", "PHONE", "PHOTO", "PHOTO_INFO_CERAMIC", "PHOTO_INFO_FULL_COLOUR", "PHOTO_INFO_LASER", "PHOTO_INFO_TRADITIONAL", "PINSTRIPES", "PREMIUM_PLANA", "PREMIUM_PLANA_DESCRIPTION", "PLANTS_AND_TREES", "PLAQUE", "PLAQUES_SIZES", "PLEASE_CONFIRM", "PLEASE_ENTER", "PLEASE_ENTER_A_CORRECT_PASSWORD", "PLEASE_CHOOSE_A_FIXING_SYSTEM_FOR_YOUR_BRONZE_PLAQUE", "PLEASE_CONFIRM_DELIVERY_DETAILS", "PLEASE_ENTER_EMAIL", "PLEASE_ENTER_FIRST_NAME", "PLEASE_ENTER_LAST_NAME", "PLEASE_ENTER_COUNTRY", "PLEASE_ENTER_STATE", "PLEASE_ENTER_POST_CODE", "PLEASE_ENTER_CITY", "PLEASE_ENTER_ADDRESS", "PLEASE_ENTER_MOBILE", "PLEASE_ENTER_LOGIN", "PLEASE_ENTER_NAME_FOR_YOUR_DESIGN", "PLEASE_ENTER_PASSWORD", "PLEASE_UPDATE_YOUR_CONTACT_DETAILS", "PLEASE_UPDATE_YOUR_INVOICE_DETAILS", "PLEASE_REPEAT_PASSWORD", "PLEASE_ENTER_POST_CODE", "PLEASE_FINALIZE_PURCHASE", "POSITION_PHOTO_AND_SIZE", "POSTCODE", "PREHISTORIC", "PRICE", "PRIVACY_POLICY", "PRIVACY_POLICY_IFRAME", "PRODUCT", "PRODUCTS", "PROMO_CODE", "QUANTITY", "QUICK_ENQUIRY", "QUICK_ENQUIRY_DESCRIPTION", "QUOTE", "RANGE", "RANDOM", "REQUIRED", "REQUIREMENTS_1", "REQUIREMENTS_2", "REGISTER", "REGISTER_INFO", "RELIGIOUS", "REPEAT_PASSWORD", "REPTILES", "RESET", "RESET_INFO", "RESET_PASSWORD", "RESET_PASSWORD_INFO_1", "ROTATE", "ROTATE_LEFT", "ROTATE_RIGHT", "ROTATION", "ROUNDED", "STRAIGHT", "SAVE", "SAVED_DESIGNS", "SAVE_DESIGN", "SCENES", "SCREWS", "SETTINGS_UPDATED", "SETTINGS_UPDATE_ERROR", "SCREWS_VISIBLE_FROM_FRONT", "SCROLLS", "SELECT", "SELECT_BORDER", "SELECT_BORDER_COLOR", "SELECT_BRONZE", "SELECT_CATEGORY", "SELECT_COLOUR", "SELECT_EMBLEM", "SELECT_FONT", "SELECT_GRANITE", "SELECT_INSTALLATION", "SELECT_INSTALLATION_DESCRIPTION", "SELECT_INSTALLATION_INSTRUCTIONS", "SELECT_MASK", "SELECT_MATERIAL", "SELECT_MOTIF", "SELECT_PHOTO", "SELECT_PRODUCT", "SELECT_PRODUCTS", "SELECT_ROTATION", "SELECT_SHAPE", "SELECT_SIZE", "SEND_DESIGN", "SEND_DESIGN_TO_FAMILY_OR_A_FRIEND", "SEND_ENQUIRY", "SEPARATE", "SEPIA", "SETTINGS", "SEE_MOCKUP", "SHAPE", "SHAPES", "SHAPES_INFO", "SHAPES_YAG", "SHAPES_AND_PATTERNS", "SHARE", "SHARED_DESIGN_EMAIL", "SHIPPING_ADDRESS", "SHIPPING_METHOD", "SILVER_LID", "STAINLESS_STEEL_LIGHT_TRANSMITTING_PLAQUE","STAINLESS_STEEL_LIGHT_REFLECTIVE_PLAQUE", "STAINLESS_STEEL_LIGHT_TRANSMITTING_PLAQUE_DESCRIPTION", "SIZE", "SIZES", "SKULLS_AND_WEAPONS", "SMALL", "SOME_CEMETERIES", "SPORT_AND_FITNESS", "STAND", "STAINLESS_STEEL_BORDER", "STAINLESS_STEEL_MOTIF", "STAINLESS_STEEL_MOTIF_DESCRIPTION", "STAINLESS_STEEL_VITREOUS_URN", "STAINLESS_STEEL_VITREOUS_URN_DESCRIPTION", "STAINLESS_STEEL_DESCRIPTION", "START_DESIGN", "STATE", "STEP", "STREET", "SWITCH", "SWITCH_MODE", "SYMBOLS_ZODIAC", "TABLET", "TEXT", "THANK_YOU_AND_CONGRATULATIONS_INVOICE", "THANK_YOU_FOR_CONTACTING_US", "THE_FIRST_MOTIF_FREE", "THERE_WAS_A_PROBLEM_CHANGING_YOUR_PASSWORD", "THICKNESS", "THIS_EMAIL_IS_ALREADY_REGISTERED", "TOOLS_OFFICE", "TOTAL", "TRADING_NAME", "TRADITIONAL_PLAQUES_SIZES", "TRADITIONAL_ENGRAVED_FULL_MONUMENT", "TRADITIONAL_ENGRAVED_FULL_MONUMENT_DESCRIPTION", "TRADITIONAL_ENGRAVED_HEADSTONE", "TRADITIONAL_ENGRAVED_HEADSTONE_DESCRIPTION", "TRADITIONAL_ENGRAVED_PLAQUE", "TRADITIONAL_ENGRAVED_PLAQUE_DESCRIPTION", "TRADITIONAL_ENGRAVED_PLAQUE_SHAPES", "TRIBAL", "TUTORIAL", "UNIT_PRICE", "UPDATE", "UPLOAD", "UPLOADING_YOUR_IMAGE", "UPLOADING_YOUR_IMAGE_FCP", "UPLOADING_YOUR_IMAGE_DESCRIPTION", "URN", "USA", "VEHICLES", "VITREOUS_ENAMEL", "VITREOUS_ENAMEL_DESCRIPTION", "VITREOUS_ENAMEL_IMAGE_OVERLAY", "WEBSITE", "WELCOME", "WELCOME_TO_DYO", "WE_WILL_COMMENCE_WITH_YOUR_ORDER", "WITH", "WIDTH", "WORLD_ANIMALS", "YAG_LASERED_STAINLESS_STEEL_PLAQUE", "YAG_LASERED_STAINLESS_STEEL_PLAQUE_DESCRIPTION", "YAG_LASERED_STAINLESS_STEEL_PLAQUE_SIZES", "YAG_LASSERED_IMAGE", "YAG_LASSERED_IMAGE_DESCRIPTION", "YES", "YOU_ARE_ABOUT_TO_GO_TO_THE_3D", "PERFORM_TESTING", "GENERATE_DESIGN","PLEASE_NOTE_3D_MODE_STILL_IN_TESTING", "CONFIRM", "DECLINE", "YOUR_CURRENT_DESIGN_WILL_BE_LOST", "YOUR_ORDERS", "YOU_HAVE_BEEN_SENT_EMAIL", "YOU_HAVE_NO_SAVED_DESIGNS", "YOUR_PASSWORD_HAS_BEEN_CHANGED", "YOUR_PHOTO_WILL_NOT_BE_SAVED", "YOUR_PRODUCT_IS_WARRANTED", "HOLD_INCREASE", "HOLD_DECREASE"];

export const Lang = {};

for (let nr = 0; nr < language.length; nr ++) {
    Lang[language[nr]] = language[nr].toLowerCase();
}

export function Translate(t) {
    if (t) {
        return dyo.config.language[t];
    }
}

export function _(a, b) {
    if (b) {
        if (b.indexOf(" ") > -1) {
            let o = b.split(" ");
            for (let n = 0; n < o.length; n++) {
                a.push(o[n]);
            }
        } else {
            a.push(b);
        }
    }

    return a;
}

export function $(id, v, w, s) {

    let node;
    if (typeof v !== 'undefined') {
        switch(v) {
            case "add":
                node = document.createElement(id);
                if (typeof w !== 'undefined') {
                    if (typeof w == "string") {
                        if (w != '') {
                            node.classList.add(w);
                        }
                    }
                    if (typeof w == "object") {
                        for (let n = 0; n < w.length; n++) {
                            node.classList.add(w[n]);
                        }
                    }
                }
                if (typeof s !== 'undefined') {
                    s.appendChild(node);
                }
                return node;
                break
            case "id":
                node = document.createElement(id);
                if (typeof w !== 'undefined') {
                    if (typeof w == "object") {
                        if (typeof w.id !== 'undefined') {
                            node.id = w.id;
                        }
                        if (typeof w.class !== 'undefined') {
                            if (typeof w.class == "string") {
                                node.classList.add(w.class);
                            }        
                            if (typeof w.class == "object") {
                                for (let n = 0; n < w.class.length; n++) {
                                    node.classList.add(w.class[n]);
                                }        
                            }
                        }
                        if (typeof w.css !== 'undefined') {
                            node.style = w.css;
                        }
                        if (typeof w.desc !== 'undefined') {
                            node.innerHTML = w.desc;
                        }
                        if (typeof w.src !== 'undefined') {
                            node.setAttribute("data-src", w.src);
                        }
                    }
                }
                if (typeof s !== 'undefined') {
                    s.appendChild(node);
                }
                if (w.serialize) {
                    return new XMLSerializer().serializeToString(node);
                } else {
                    return node;
                }
                break;
            case "value":
                if (document.querySelector(id)) {
                    document.querySelector(id).value = w;
                }
                break
            default:
                if (document.querySelector(id)) {
                    document.querySelector(id).innerHTML = v;
                }
                break;
        }
    } else {
        if (document.querySelector(id)) {
            return document.querySelector(id);
        }
    }
}

export function Serialize(node) {
    return new XMLSerializer().serializeToString(node);
}

export function File(f) {
    return dyo.monument._shapes[0].files[f];
}

export function Metric() {

    let m = {};
    m.step = 1;

    switch (dyo.metric) {
        case "inches":
            m.metric = Lang.INCHES;
            m.step = dyo.engine.metrics.getMMtoInch() / 4;
            break;
        case "mm":
            m.metric = Lang.MM;
            m.step = 1;
            break;
    }

    return m;

}